Add keyword check

diff --git a/.github/workflows/check-n-lines-changed.yaml b/.github/workflows/check-n-lines-changed.yaml
--- a/.github/workflows/check-n-lines-changed.yaml
+++ b/.github/workflows/check-n-lines-changed.yaml
@@ -4,6 +4,7 @@ env:
   MAX_LINES_ADDED: 300
   MAX_LINES_REMOVED: 500
   OVERRIDE_N_APPROVALS: 2
+  RECHECK_COMMAND: '/recheck-n-lines'
 jobs:
   check-n-lines-changed:
     # yamllint disable rule:indentation
@@ -23,6 +24,20 @@ jobs:
     - uses: 'actions/checkout@v4'
       with:
         fetch-depth: 0
+    # Verify the keyword used to trigger the action from a comment, since the
+    # above `if` check requires a hard-coded value.
+    - id: 'verify-keyword'
+      # yamllint disable rule:indentation
+      run: |
+        if [ "${{ github.event_name }}" = "issue_comment" ]; then
+          BODY="${{ github.event.comment.body }}"
+          COMMAND="${{ env.RECHECK_COMMAND }}"
+          if ! echo "$BODY" | grep -q "$COMMAND"; then
+            echo "Invalid keyword trigger. Should be $COMMAND"
+            exit 1
+          fi
+        fi
+    # yamllint enable rule:indentation
     - id: 'get-pr-number'
       name: 'Get PR number'
       # yamllint disable rule:indentation
@@ -100,7 +115,7 @@ jobs:
             echo "✅ Changes exceeded limits but have required approvals"
           else
             echo "❌ Too many changes. Need $OVERRIDE_N_APPROVALS approvals"
-            echo "Trigger a recheck by commenting '/recheck-n-lines'"
+            echo "Trigger a recheck by commenting '$RECHECK_COMMAND'"
             exit 1
           fi
         else
